version: '0.2.0+{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
branches:
  only:
    - master
skip_commits:
  files:
  - '**/*.md'

build:
  verbosity: minimal
install:
  - choco install opencover codecov


build_script:
  - dotnet build -c Release
  - dotnet pack --no-build -c Release /p:PackageOutputPath=..\..\.nupkgs
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test test/DevTo.Api.Tests/DevTo.Api.Tests.csproj /p:DebugType=Full" -filter:"+[DevTo.Api]* -[DevTo.Api.Tests]*" -output:".\coverage.xml" -oldstyle
  - codecov -f coverage.xml


artifacts:
  - path: '.nupkgs\*.nupkg'

  - path: coverage.xml
    name: Coverage Report